services:
  postgres_primary:
    image: postgres:17
    container_name: postgres_primary
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ThZ3d1112
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./src/main/resources/persistence/init.sql:/docker-entrypoint-initdb.d/01_init.sql
      - ./src/main/resources/persistence/setup_replication.sh:/docker-entrypoint-initdb.d/02_setup_replication.sh
      - primary_data:/var/lib/postgresql/data
    networks:
      - zoopolis_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres_replica:
    image: postgres:17
    container_name: postgres_replica
    environment:
      PGPASSWORD: replicator_pass
      POSTGRES_PASSWORD: ThZ3d1112  # Necessário para o pg_isready
      PGDATA: /var/lib/postgresql/data
    volumes:
      - replica_data:/var/lib/postgresql/data
    networks:
      - zoopolis_network
    depends_on:
      postgres_primary:
        condition: service_healthy
    # COMANDO CORRIGIDO (Com ponto e vírgula e password exportada)
    command: >
      bash -c "
      export PGPASSWORD=$POSTGRES_PASSWORD;
      until pg_isready -h postgres_primary -U postgres; do 
        echo 'A aguardar Primary...'; sleep 2; 
      done;
      
      if [ -z \"$(ls -A /var/lib/postgresql/data)\" ] || [ ! -f /var/lib/postgresql/data/standby.signal ]; then
          echo 'Iniciando clonagem do Primary...';
          rm -rf /var/lib/postgresql/data/*;
          pg_basebackup -h postgres_primary -U replicator -D /var/lib/postgresql/data -Fp -Xs -P -R;
          chmod 700 /var/lib/postgresql/data;
      fi;
      
      echo 'Iniciando Replica...';
      docker-entrypoint.sh postgres
      "

  haproxy:
    image: haproxy:latest
    container_name: haproxy_lb
    ports:
      - "5432:5432"
      - "8081:8081"
      - "8404:8404"
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    networks:
      - zoopolis_network
    depends_on:
      - postgres_primary
      - postgres_replica
    healthcheck:
      test: ["CMD-SHELL", "haproxy -c -f /usr/local/etc/haproxy/haproxy.cfg"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 10s

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      replicas: 2
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://haproxy:5432/postgres?currentSchema=zoopolis&targetServerType=preferSlave&connectTimeout=5
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ThZ3d1112
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SERVER_PORT: 8081
    networks:
      - zoopolis_network
    depends_on:
      haproxy:
        condition: service_healthy

networks:
  zoopolis_network:
    driver: bridge

volumes:
  primary_data:
  replica_data: